name: health_companion
description: Personal Health Companion — offline-first health & disaster-resilience app (SIH '26 #26181).
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.12
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  permission_handler: ^11.3.1
  fl_chart: ^0.68.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
